### PR TITLE
[Feature] replaced constant loading with on demand loading

### PR DESCRIPTION
**Pull request by nLatt**
Replaces how we load animations, they only loaded when we need them.

### CODE REVIEW

**Comment by mindoodoo** [comment]
Are each texture loaded only once, or multiple times for each time we want to draw an instance of that structure ?

**Comment by nLatt** [comment]
only once

**Comment by mindoodoo** [comment]
Would merge, but no label, so not merging ISSSOUUU

**Review by mindoodoo — APPROVED** [review]

**Comment by nLatt** [comment]
Your relatives are goblins.

**Comment by mindoodoo** [comment]
AT LEAST I HAVE RELATIVES

**Comment by nLatt** [comment]
:c

**Comment by nLatt** [comment]
sadge

**Comment by mindoodoo** [comment]
ehehe

**Pull request merged**
