### PR TITLE
40 add root class for client and server

### PR DESCRIPTION
**Pull request by mindoodoo**
### This PR adds the following

- Refactor of the Communication class into the UDPCommunication class
- Addition of base class Server for the server, and Client for the client
- Addition of Game class for the server and ClientGame for the client

The main idea behind this structure is that while no game is launched, each program will instantiate and execute the main loop of their "base class", which will then instantiate and execute the main loop of the "game class" once the lobby has filled up and the game is ready to start.

### CODE REVIEW

**Comment by nLatt** [comment]
You get any of dem labels?

**Comment by nLatt** [comment]
Code looks solid otherwise, I'd suggest renaming UDPCommunication to GameCommunication tho

**Comment by mindoodoo** [comment]
> I'd suggest renaming UDPCommunication to GameCommunication tho

The issue is that it is really only a base class that abstracts the handling of the udp side of things. There will be the GameProtocol class. Also since we will have both TCP and UDP in the server and client, it makes sense to be able to easily distinguish which is which at least on some level.

Otherwise, you like dem labels ?

**Comment by mindoodoo** [comment]
@nLatt This is ready to merge, but for some reason the build is failing in windows. Could you take a look at it ?

**Review by nLatt — APPROVED** [review]
I read the code, I agree, it is very good, nya~

**Pull request merged**
